### PR TITLE
Add support for 'hh:mm' format

### PR DESCRIPTION
**Pull request by YahiaElTai**
i have added the functionality requested by the issue #3, also added the tests and they all work properly, and also updated the README.md file. 
check it out!

### CODE REVIEW

**Review by Goldob — CHANGES_REQUESTED** [review]
Thanks for the submission. Please apply the following improvements before this can be merged:

1. We don't want to break backwards compatibility. In particular, all the tests that existed beforehand must work in unchanged form. You need to leave them unaltered and only add tests that are needed to cover the new feature.

2. All the conversions are supposed to be symmetrical. Please make `toS()` and `toMs()` functions work properly with the new format. Since there will be ambiguity between `hh:mm` and `mm:ss`, you might need to add a new argument for format specification. Don't forget to default to the old behavior so that we don't break backwards compatibility. Also, add tests reflecting the changes.

3. Comments in the code should only reflect how it works, not what you changed. The latter is only meaningful in the context of this PR and might be confusing for someone reading the code in the future. If you want to describe in detail what you changed and why, please do that [in the PR](https://help.github.com/articles/commenting-on-a-pull-request).

**Comment by YahiaElTai** [comment]
Thank you for the well-detailed feedback. i'll start working on it now.

**Comment by YahiaElTai** [comment]
@Goldob  hello again, and thank you for taking the time to review my changes: 
i added the backward compatibility to all the code and all initial tests are working, also the new 10 tests that i added just to make sure everything is working in both directions. 
i hope you like everything and if there's anything just let me know and i'll fix it.

**Comment by Goldob** [comment]
Looks good at first glance. I'll look deeper into the code some time later and let you know.

**Review by Goldob — CHANGES_REQUESTED** [review]
First of all, great job. It's nearly good to go.

I'm thinking about replacing _string_ with _format_ parameter in `toS()` and `toMs()` for the sake of consistency. Ideally, doing `toMs(fromMs(ms, format), format)` for any `ms` integer and any supported `format` string should return the exact same number (`ms`) we started with. The same goes with `toS(fromS(s, format), format)`. Do you think you can do that?

**Comment by YahiaElTai** [comment]
I think i can do that. I'll give it a go and let you know. Thanks

**Comment by YahiaElTai** [comment]
@Goldob hey again, i made the necessary change and kept all your test and my pervious tests and all of them are passing and also i added a few tests for the symmetrical conversions just like your example above. take a look at it, hope you like it. if anything is required please let me know. thanks

**Review by Goldob — APPROVED** [review]
Sweet, thank you for the good work. Expect a merge and new release some time soon.

**Comment by YahiaElTai** [comment]
My pleasure, that would be great. If you have any thing else for me let me know.

**Pull request merged**
